name: Enviar Email
on: [push]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script de envio de e-mail
        env:
          EMAIL_USUARIO: ${{ secrets.EMAIL_USUARIO }}
          SENHA: ${{ secrets.SENHA }}
        run: python app/automation/index.py